# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='origen',
        ),
    ]
