# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0002_auto_20170506_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=20000)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
