# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktapp', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200000)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
